package filler

import (
	model "github.com/n31t/go-project/pkg/model"
)

func FillDatabase(models model.Models) error {
	for _, anime := range animes {
		err := models.Animes.Insert(&anime)
		if err != nil {
			return err
		}
	}
	return nil
}

var animes = []model.Anime{
	{Title: "Naruto", Episodes: 220, Studio: "Studio Pierrot", Description: "Naruto is a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village.", ReleaseYear: 2002, Genre: "Shounen", Rating: 8.3},
	{Title: "Fate/Zero", Episodes: 25, Studio: "ufotable", Description: "The Holy Grail War is a battle royale among seven magi who serve as Masters. Masters, through the use of the command seals they are given when they enter the war, command Heroic Spirits known as Servants to fight for them in battle.", ReleaseYear: 2011, Genre: "Action", Rating: 8.3},
	{Title: "Attack on Titan", Episodes: 75, Studio: "Wit Studio", Description: "The series follows the story of Eren Yeager, who vows to retake the world after a Titan brings about the destruction of his home town and the death of his mother.", ReleaseYear: 2013, Genre: "Action", Rating: 8.3},
	{Title: "Fate/stay night: Unlimited Blade Works", Episodes: 26, Studio: "ufotable", Description: "The Holy Grail War is a battle royale among seven magi who serve as Masters. Masters, through the use of the command seals they are given when they enter the war, command Heroic Spirits known as Servants to fight for them in battle.", ReleaseYear: 2014, Genre: "Action", Rating: 8.3},
	{Title: "Fate/stay night: Heaven's Feel", Episodes: 3, Studio: "ufotable", Description: "The Holy Grail War is a battle royale among seven magi who serve as Masters. Masters, through the use of the command seals they are given when they enter the war, command Heroic Spirits known as Servants to fight for them in battle.", ReleaseYear: 2017, Genre: "Action", Rating: 8.3},
	{Title: "Higurashi no Naku Koro ni", Episodes: 26, Studio: "Studio Deen", Description: "The story of Higurashi no Naku Koro ni is divided into a total of eight chapters: four 'Question' arcs and four 'Answer' arcs. Each chapter keeps the same main characters, but ends in a different way.", ReleaseYear: 2006, Genre: "Horror", Rating: 8.3},
	{Title: "Steins;Gate", Episodes: 24, Studio: "White Fox", Description: "The story of Steins;Gate takes place in Akihabara and is about a group of friends who have customized their microwave into a device that can send text messages to the past.", ReleaseYear: 2011, Genre: "Sci-Fi", Rating: 8.3},
	{Title: "Death Note", Episodes: 37, Studio: "Madhouse", Description: "The story follows Light Yagami, a teen genius who stumbles across a mysterious otherworldly notebook: the 'Death Note', which belonged to the Shinigami Ryuk and grants the user the supernatural ability to kill anyone whose name is written in its pages.", ReleaseYear: 2006, Genre: "Mystery", Rating: 8.3},
	{Title: "Code Geass: Lelouch of the Rebellion", Episodes: 50, Studio: "Sunrise", Description: "The series is set in an alternative future where the world is split into three superpowers, Britannia, the Chinese Federation, and the European Union. The story takes place after the Holy Britannian Empire's conquest on Japan in August 10, 2010 a.t.b., by means of Britannia's newest weapon, the 'Autonomous Armored Knight', or 'Knightmare Frame'.", ReleaseYear: 2006, Genre: "Mecha", Rating: 8.3},
	{Title: "Fate/Apocrypha", Episodes: 25, Studio: "A-1 Pictures", Description: "The story is set in a parallel world to original Fate/stay night, where the House of Einzbern summoned a Ruler rather than an Avenger in the Third Holy Grail War, and the Holy Grail was removed from Fuyuki City to Romania after the war.", ReleaseYear: 2017, Genre: "Action", Rating: 8.3},
	{Title: "Fate/stay night", Episodes: 24, Studio: "Studio Deen", Description: "The Holy Grail War is a battle royale among seven magi who serve as Masters. Masters, through the use of the command seals they are given when they enter the war, command Heroic Spirits known as Servants to fight for them in battle.", ReleaseYear: 2006, Genre: "Action", Rating: 8.3},
	{Title: "Fate/kaleid liner Prisma Illya", Episodes: 10, Studio: "Silver Link", Description: "Illyasviel von Einzbern is a normal schoolgirl in Japan. She lives with her overachieving nice guy older brother Shirou Emiya and her two maids, her parents are perpetually out of the country, and she has fanciful dreams of using magic to make her dreams of love with Shirou come true.", ReleaseYear: 2013, Genre: "Action", Rating: 8.3},
	{Title: "Land of the Lustrous", Episodes: 12, Studio: "Orange", Description: "In the distant future, a new life form called Houseki (gems) are born. The 28 Houseki must fight against the Moon Dwellers, who want to attack them and turn them into decorations, so each gem is assigned a role such as a fighter or a medic. Though he hopes to fight the Moon Dwellers, Phos is a gem who is given no assignment until the gems' master Adamantine asks him to edit a natural history magazine.", ReleaseYear: 2017, Genre: "Action", Rating: 8.3},
	{Title: "Oshi no Ko", Episodes: 12, Studio: "MAPPA", Description: "The story follows the lives of two people, a former scientist and a former child actor, who are trying to uncover the truth behind the mysterious deaths of idols.", ReleaseYear: 2021, Genre: "Drama", Rating: 8.3},
	{Title: "The Promised Neverland", Episodes: 23, Studio: "CloverWorks", Description: "The story follows a group of orphaned children in their escape plan from a farm. The farm they live in is run by demons and the children are raised as food for them.", ReleaseYear: 2019, Genre: "Horror", Rating: 8.3},
	{Title: "Higurashi no Naku Koro ni Gou", Episodes: 24, Studio: "Passione", Description: "The story of Higurashi no Naku Koro ni is divided into a total of eight chapters: four 'Question' arcs and four 'Answer' arcs. Each chapter keeps the same main characters, but ends in a different way.", ReleaseYear: 2020, Genre: "Horror", Rating: 8.3},
	{Title: "Date A Live", Episodes: 34, Studio: "AIC Plus+", Description: "The story follows Shido Itsuka, a seemingly ordinary high school student who comes across a mysterious", ReleaseYear: 2013, Genre: "Romance", Rating: 8.3},
	{Title: "Fate/Grand Order", Episodes: 21, Studio: "CloverWorks", Description: "The story is set in the year 2015, during the final era over which magic still held a strong influence. The humanity survival and security organization Chaldea was established to observe the world that can only be seen by magic and the world that can only be measured by science; as well as to prevent the final extinction of humanity.", ReleaseYear: 2019, Genre: "Action", Rating: 8.3},
	{Title: "Naruto: Shippuden", Episodes: 500, Studio: "Studio Pierrot", Description: "Naruto: Shippuden is an anime series adapted from Part II of Masashi Kishimoto's manga series, with exactly 500 episodes. It is set two and a half years after Part I in the Naruto universe, following the ninja teenager Naruto Uzumaki and his allies.", ReleaseYear: 2007, Genre: "Shounen", Rating: 8.3},
	{Title: "The Rising of the Shield Hero", Episodes: 25, Studio: "Kinema Citrus", Description: `The story follows Naofumi Iwatani, an otaku who is suddenly summoned to a parallel universe along with three other 
	heroes to become the world's Cardinal Heroes and fight inter-dimensional hordes of monsters called Waves.`, ReleaseYear: 2019, Genre: "Action", Rating: 8.3},
	{Title: "Re:Zero", Episodes: 50, Studio: "White Fox", Description: "The story centers on Subaru Natsuki, a hikikomori who suddenly finds himself transported to another world on his way home from the convenience store. The series was initially serialized on the website Shōsetsuka ni Narō from 2012 onwards.", ReleaseYear: 2016, Genre: "Action", Rating: 8.3},
	{Title: "Attack on Titan: The Final Season", Episodes: 16, Studio: "MAPPA", Description: "The series follows the story of Eren Yeager, who vows to retake the world after a Titan brings about the destruction of his home town and the death of his mother.", ReleaseYear: 2020, Genre: "Action", Rating: 8.3},
	{Title: "Overlord", Episodes: 39, Studio: "Madhouse", Description: "The story begins with Yggdrasil, a popular online game which is quietly shut down one day. However, the protagonist Momonga decides to not log out. Momonga is then transformed into the image of a skeleton as 'the most powerful wizard.' The world continues to change, with non-player characters (NPCs) beginning to feel emotion. Having no parents, friends, or place in society, this ordinary, everyday young", ReleaseYear: 2015, Genre: "Action", Rating: 8.3},
	{Title: "Attack on Titan: Junior High", Episodes: 12, Studio: "Production I.G", Description: "The series follows the story of Eren Yeager, who vows to retake the world after a Titan brings about the destruction of his home town and the death of his mother.", ReleaseYear: 2015, Genre: "Comedy", Rating: 8.3},
	{Title: "Berserk", Episodes: 25, Studio: "OLM", Description: "The story follows Guts, a lone mercenary warrior, and Griffith, the leader of a mercenary band called the Band of the Hawk. Themes of isolation, camaraderie, and the question of whether humanity is fundamentally good or evil pervade the story, as it explores both the best and worst of human nature.", ReleaseYear: 1997, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai", Episodes: 7, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2007, Genre: "Action", Rating: 8.3},
	{Title: "Fate/stay night: Heaven's Feel II. Lost Butterfly", Episodes: 1, Studio: "ufotable", Description: "The Holy Grail War is a battle royale among seven magi who serve as Masters. Masters, through the use of the command seals they are given when they enter the war, command Heroic Spirits known as Servants to fight for them in battle.", ReleaseYear: 2019, Genre: "Action", Rating: 8.3},
	{Title: "Fate/stay night: Heaven's Feel III. Spring Song", Episodes: 1, Studio: "ufotable", Description: "The Holy Grail War is a battle royale among seven magi who serve as Masters. Masters, through the use of the command seals they are given when they enter the war, command Heroic Spirits known as Servants to fight for them in battle.", ReleaseYear: 2020, Genre: "Action", Rating: 8.3},
	{Title: "Fate/stay night: Unlimited Blade Works - Sunny Day", Episodes: 1, Studio: "ufotable", Description: "The Holy Grail War is a battle royale among seven magi who serve as Masters. Masters, through the use of the command seals they are given when they enter the war, command Heroic Spirits known as Servants to fight for them in battle.", ReleaseYear: 2015, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai: Mirai Fukuin", Episodes: 1, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2013, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai: Mirai Fukuin - Extra Chorus", Episodes: 1, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2013, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai: The Garden of Sinners", Episodes: 1, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2007, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai: The Garden of Sinners - A Study", Episodes: 1, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2007, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai: The Garden of Sinners - Remaining Sense of Pain", Episodes: 1, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2008, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai: The Garden of Sinners - Oblivion Recording", Episodes: 1, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2008, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai: The Garden of Sinners - Paradox Paradigm", Episodes: 1, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2008, Genre: "Action", Rating: 8.3},
	{Title: "Kara no Kyoukai: The Garden of Sinners - Recalled Out Summer", Episodes: 1, Studio: "ufotable", Description: "The series is regarded as being set in an alternate parallel universe to Type-Moon's other series, Tsukihime and Fate/stay night, and the story centers on the magecraft and supernatural occurrences in the Mifune City.", ReleaseYear: 2008, Genre: "Action", Rating: 8.3},
	{Title: "Puella Magi Madoka Magica", Episodes: 12, Studio: "Shaft", Description: "The story follows a group of girls who gain magical powers and battle against witches. They are led by Madoka Kaname, who is granted a wish in exchange for her soul.", ReleaseYear: 2011, Genre: "Magic", Rating: 8.3},
	{Title: "Puella Magi Madoka Magica: The Movie -Rebellion-", Episodes: 1, Studio: "Shaft", Description: "The story follows a group of girls who gain magical powers and battle against witches. They are led by Madoka Kaname, who is granted a wish in exchange for her soul.", ReleaseYear: 2013, Genre: "Magic", Rating: 8.3},
	{Title: "Puella Magi Madoka Magica: The Movie -Beginnings-", Episodes: 1, Studio: "Shaft", Description: "The story follows a group of girls who gain magical powers and battle against witches. They are led by Madoka Kaname, who is granted a wish in exchange for her soul.", ReleaseYear: 2012, Genre: "Magic", Rating: 8.3},
	{Title: "Bakemonogatari", Episodes: 15, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2009, Genre: "Mystery", Rating: 8.3},
	{Title: "Nisemonogatari", Episodes: 11, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2012, Genre: "Mystery", Rating: 8.3},
	{Title: "Nekomonogatari: Kuro", Episodes: 4, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2012, Genre: "Mystery", Rating: 8.3},
	{Title: "Monogatari Series: Second Season", Episodes: 23, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2013, Genre: "Mystery", Rating: 8.3},
	{Title: "Hanamonogatari", Episodes: 5, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2014, Genre: "Mystery", Rating: 8.3},
	{Title: "Tsukimonogatari", Episodes: 4, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2014, Genre: "Mystery", Rating: 8.3},
	{Title: "Owarimonogatari", Episodes: 12, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2015, Genre: "Mystery", Rating: 8.3},
	{Title: "Kizumonogatari", Episodes: 3, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2016, Genre: "Mystery", Rating: 8.3},
	{Title: "Koyomimonogatari", Episodes: 12, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2016, Genre: "Mystery", Rating: 8.3},
	{Title: "Owarimonogatari 2nd Season", Episodes: 7, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2017, Genre: "Mystery", Rating: 8.3},
	{Title: "Zoku Owarimonogatari", Episodes: 6, Studio: "Shaft", Description: "The story follows Koyomi Araragi, a high school student who is almost human again after briefly becoming a vampire. One day, a classmate named Hitagi Senjōgahara, who never talks to anyone, falls down the stairs into Koyomi's arms.", ReleaseYear: 2018, Genre: "Mystery", Rating: 8.3},
	{Title: "Kiznaiver", Episodes: 12, Studio: "Trigger", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 2016, Genre: "Drama", Rating: 8.3},
	{Title: "Darling in the Franxx", Episodes: 24, Studio: "A-1 Pictures", Description: "The story is set in a distant future where humanity is on the brink of extinction due to the appearance of giant creatures known as klaxosaurs, which force humanity to abandon Earth for the space colonies Plantations. On one of these plantations, children are artificially created in Mistilteinn, a facility overseen by the APE, which is at war with the klaxosaurs.", ReleaseYear: 2018, Genre: "Mecha", Rating: 8.3},
	{Title: "Evangelion: 1.0 You Are (Not) Alone", Episodes: 1, Studio: "Khara", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 2007, Genre: "Mecha", Rating: 8.3},
	{Title: "Evangelion: 2.0 You Can (Not) Advance", Episodes: 1, Studio: "Khara", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 2009, Genre: "Mecha", Rating: 8.3},
	{Title: "Evangelion: 3.0 You Can (Not) Redo", Episodes: 1, Studio: "Khara", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 2012, Genre: "Mecha", Rating: 8.3},
	{Title: "Evangelion: 3.0+1.0 Thrice Upon a Time", Episodes: 1, Studio: "Khara", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 2021, Genre: "Mecha", Rating: 8.3},
	{Title: "Neon Genesis Evangelion", Episodes: 26, Studio: "Gainax", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 1995, Genre: "Mecha", Rating: 8.3},
	{Title: "Rebuild of Evangelion", Episodes: 4, Studio: "Khara", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 2007, Genre: "Mecha", Rating: 8.3},
	{Title: "Evangelion: Death and Rebirth", Episodes: 1, Studio: "Gainax", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 1997, Genre: "Mecha", Rating: 8.3},
	{Title: "Evangelion: The End of Evangelion", Episodes: 1, Studio: "Gainax", Description: "The story follows a group of high school students who are chosen to be a part of an experimental program which creates bonds between people by forcing them to share each other's pain.", ReleaseYear: 1997, Genre: "Mecha", Rating: 8.3},
}
